export enum ProductFiltre {
  MOST_REQUESTED = 'MOST_REQUESTED',
  NEW_ARRIVAL = 'NEW_ARRIVAL',
  ASCENDING_PRICE = 'ASCENDING_PRICE',
  DECREASING_PRICE = 'DECREASING_PRICE',
  TOP_RATED = 'TOP_RATED'
}
