export enum RoleType {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SELLER = 'SELLER',
  BUYER = 'BUYER',
  SELLER_BUYER = 'SELLER_BUYER',
  TECHNICALSUPPORT = 'TECHNICALSUPPORT',
  DELIVERYAGENCY = 'DELIVERYAGENCY',
  AFTERSALESSUPPORT = 'AFTERSALESSUPPORT',
  DELIVERYMEN = 'DELIVERYMEN',
  SUPPLIER = 'SUPPLIER'
}
