import {GenderType} from "./Enum/GenderType";
import {Order} from "./Order";
import {Store} from "./Store";
import {Role} from "./Role";
import {ClaimSav} from "./ClaimSav";
import {Review} from "./Review";
import {AgencyBranch} from "./AgencyBranch";
import {SupplierRequest} from "./SupplierRequest";

export class User {
  id!: number;
  firstName!: string;
  lastName!: string;
  email!: string;
  password!: string;
  enabled!: boolean;
  tokenExpired!: boolean;
  banned!: boolean;
  phoneNumber!: string;
  BirthDate!: Date;
  image!: string;
  genderType!: GenderType;
  identity!: string;
  brandName!: string;
  brandLogo!: string;
  justification!: string;
  governorate!: string;
  city!: string;
  gear!: string;
  driveLicense!: string;
  GearAge!: number;
  co2!: number;
  resetToken!: number;
  rating!: number;
  numberOfRatings!: number;
  levelDelivery!: string;
  orders: Order[] = [];
  stores: Store[] = [];
  role!: Role;
  claimSavList: ClaimSav[] = [];
  reviewsSent: Review[] = [];
  reviewsOnDA: Review[] = [];
  reviewsOnDF: Review[] = [];
  requestsdeliverymen: Request[] = [];
  requestsellers: Request[] = [];
  requestsAgencys: Request[] = [];
  agencyBranches: AgencyBranch[] = [];
  supplierRequests: SupplierRequest[] = [];
}
